### ISSUE TITLE
chgrp: cannot access '/app/public/uploads': No such file or directory

### ISSUE THREAD

**Issue by micos7** [appelsiini/laravel-ctf-exercise#1]
Step 11/16 : RUN chgrp -R daemon /app/storage /app/public/uploads /app/bootstrap/cache
 ---> Running in faea6d3656ca
chgrp: cannot access '/app/public/uploads': No such file or directory
ERROR: Service 'app' failed to build: The command '/bin/sh -c chgrp -R daemon /app/storage /app/public/uploads /app/bootstrap/cache' returned a non-zero code: 1

I cloned it locally and this is what I get after running sudo docker-compose build. Thank you for your time.

**Comment by appelsiini** [comment]
Thanks for noticing this, fixed directly to master. ✌️
